#!/bin/sh

log() {
  echo
  echo "$1"
  echo
}

for test in $(dirname $0)/*_test.sh; do
  log ">>> Running $test"
  $SHELL $test
  echo '------------------------------------------------------------'
done
